name: Update submodules

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Pull submodules
      run: "git submodule update --init --recursive"

    - name: Update submodules
      run: "git submodule foreach --recursive --quiet pwd | xargs -P10 -I{} bash -c 'cd {}; git checkout master && git pull'"

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update submodules
        commit_options: '--no-verify --signoff'
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com
        commit_author: GitHub Actions <actions@github.com>
